[package]
name = "impostor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "impostor"
crate-type = ["cdylib"]

[dependencies]
alum = "0.6.1"
glam = "0.30.4"
pyo3 = "0.25.0"
