[workspace]
members = ["crates/*", "demos/*"]
resolver = "2"
license = "MIT OR Apache-2.0"

[profile.dev.package.bevy_rapier3d]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
