[project]
name = "impostor"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "Andras Polgar", email = "azazdeaz@gmail.com" }]
requires-python = "==3.12.*"
dependencies = [
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "evotorch>=0.5.1,<0.6",
    "ipykernel>=6.29.5,<7",
    "jupyter>=1.1.1,<2",
    "torchviz>=0.0.3,<0.0.4",
    "numpy>=2.1.1,<3",
    "rerun-sdk>=0.21.0,<0.22",
    "scipy>=1.14.1,<2",
    "pyyaml>=6.0.2,<7",
    "pydantic>=2.11.3",
    "doit>=0.36.0",
    "ryven>=3.5.0",
    "pyside6>=6.9.0",
]
readme = "README.md"
license = { text = "MIT" }

