[project]
name = "impostor"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "Andras Polgar", email = "azazdeaz@gmail.com" }]
requires-python = "==3.12.*"
dependencies = [
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "evotorch>=0.5.1,<0.6",
    "ipykernel>=6.29.5,<7",
    "jupyter>=1.1.1,<2",
    "torchviz>=0.0.3,<0.0.4",
    "numpy>=2.1.1,<3",
    "rerun-sdk>=0.21.0,<0.22",
    "scipy>=1.14.1,<2",
    "pyyaml>=6.0.2,<7",
]
readme = "README.md"
license = { text = "MIT" }

[[tool.pdm.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121"
include_packages = ["torch", "torchvision"]

[tool.pdm]
distribution = false

[tool.pdm.dev-dependencies]
dev = ["ruff>=0.8.3,<0.9"]

[tool.pdm.scripts]
start = "python -m impostor.run_strawberry"
setup-vscode = "python scripts/setup_vscode.py"
register-jupyter-kernel = "ipython kernel install --user --name=impostor-pdm --display-name='Impostor PDM'"

# Special note for PyTorch dependencies
# PDM doesn't support index URLs in pyproject.toml directly
# You'll need to add them manually with:
# pdm add torch torchvision --extra-index-url https://download.pytorch.org/whl/cu121
