[project]
authors = [{ name = "Polgar Andras", email = "azazdeaz@gmail.com" }]
dependencies = []
description = "Add a short description here"
name = "impostor"
requires-python = ">=3.10,<3.11"
version = "0.1.0"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
# impostor = { path = ".", editable = true }

torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu121" }
torchvision = { version = ">=0.20.1", index = "https://download.pytorch.org/whl/cu121" }
evotorch = ">=0.5.1, <0.6"
ipykernel = ">=6.29.5, <7"
jupyter = ">=1.1.1, <2"
torchviz = ">=0.0.3, <0.0.4"
tensorboard = ">=2.18.0, <3"

[tool.pixi.tasks]
start = "python -m impostor.run_strawberry"
setup-vscode = "run python scripts/setup_vscode.py"
register-jupyter-kernel = "ipython kernel install --user --name=impostor-pixi --display-name='Impostor Pixi'"

[tool.pixi.dependencies]
ruff = ">=0.8.3,<0.9"
numpy = ">=2.1.1,<3"
pip = ">=24.2,<25"
rerun-sdk = ">=0.21.0,<0.22"
scipy = ">=1.14.1,<2"
pyyaml = ">=6.0.2,<7"
# pixi-kernel = ">=0.6.0,<0.7"
ipykernel = ">=6.29.5,<7"
jupyter = ">=1.1.1,<2"
