[package]
name = "impostor-msgs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gen-msgs"
path = "src/gen_msgs.rs"

[dependencies]
bincode = "1.3.3"
serde = "1.0.210"
serde-generate = "0.26.0"
serde-reflection = "0.4.0"